spring.application.name=READORA
server.port=8082


#MYSQL Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/readora?sslMode=VERIFY_IDENTITY
spring.datasource.username=Ye4vtfeg15sWKZe.root
spring.datasource.password=R96gjTvQqfA2zdBN

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.devtools.restart.enabled=false

# ==========================================
# GMAIL SMTP
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=readora.reading@gmail.com
spring.mail.password=uazh aiir pdzs nysj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ==========================================
# JWT
# ==========================================
jwt.secret=READORA-2026-JWT-SECRET-CHANGE-THIS-TO-A-LONG-RANDOM-VALUE-1234567890